"""empty message

Revision ID: 28f8a919147e
Revises: 
Create Date: 2023-04-05 09:41:38.364909

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '28f8a919147e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('non_player_characters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('npc_name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('player_characters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pc_name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('password', sa.String(), nullable=True),
    sa.Column('campaign_id', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('campaigns',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('campaign_name', sa.String(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('non_player_character_id', sa.Integer(), nullable=True),
    sa.Column('player_character_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['non_player_character_id'], ['non_player_characters.id'], name=op.f('fk_campaigns_non_player_character_id_non_player_characters')),
    sa.ForeignKeyConstraint(['player_character_id'], ['player_characters.id'], name=op.f('fk_campaigns_player_character_id_player_characters')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_campaigns_user_id_users')),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('campaigns')
    op.drop_table('users')
    op.drop_table('player_characters')
    op.drop_table('non_player_characters')
    # ### end Alembic commands ###
